[env:esp32c3_arduino]
platform  = espressif32@6.9.0
framework = arduino
board = esp32-c3-devkitm-1
build_flags =
	-Iinclude
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
upload_protocol = esptool
upload_port = COM7
monitor_port = COM7
monitor_speed = 115200
upload_speed = 115200
monitor_filters = default, direct
monitor_dtr = 0
monitor_rts = 0