[env:esp32c3_arduino]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; Configuración de memoria (Indispensable para usar BLE + WiFi)
board_build.partitions = huge_app.csv

build_flags =
    -DPROJECT_PULSERA
; USB Nativo para la Super Mini
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
; Optimización para ahorrar energía
    -D CORE_DEBUG_LEVEL=0

lib_deps =
; --- Sensores (Magnetómetro y Acelerómetro) ---
; Usaremos las de Adafruit que son las más estables
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit HMC5883 Unified @ ^1.2.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    Wire

; --- Comunicación y Motores ---
; (ESP-Now y Motores se manejan con librerías nativas de Arduino/ESP32)
; Para BLE usaremos la integrada, pero si necesitas una más ligera:
; h2zero/NimBLE-Arduino @ ^1.4.1

[platformio]
description = Proyecto ACPI - Pulsera de navegación asistida